# Generated by Django 4.2.7 on 2025-12-08 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('pdf', 'PDF'), ('web', 'Page Web')], max_length=20, verbose_name='Type')),
                ('file', models.FileField(blank=True, null=True, upload_to='content/%Y/%m/', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, help_text='Pour les contenus web', null=True, verbose_name='URL')),
                ('duration', models.IntegerField(default=10, help_text="Durée d'affichage en secondes", verbose_name='Durée')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Taille du fichier')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Checksum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Contenu',
                'verbose_name_plural': 'Contenus',
                'ordering': ['-created_at'],
            },
        ),
    ]
