# Generated by Django 4.2.7 on 2025-12-08 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('location', models.CharField(max_length=300, verbose_name='Emplacement')),
                ('api_token', models.CharField(max_length=100, unique=True, verbose_name='Token API')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('offline', 'Hors ligne')], default='inactive', max_length=20, verbose_name='Statut')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name="Version de l'app")),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Info appareil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500, verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Écran',
                'verbose_name_plural': 'Écrans',
                'ordering': ['-created_at'],
            },
        ),
    ]
