# Generated by Django 5.2.8 on 2025-12-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
