# Generated by Django 4.2.7 on 2025-12-08 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screens', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('weekdays', models.CharField(default='0,1,2,3,4,5,6', help_text='0=Lundi, 6=Dimanche. Séparés par des virgules', max_length=50, verbose_name='Jours de la semaine')),
                ('priority', models.IntegerField(default=0, help_text='Plus le nombre est élevé, plus la priorité est haute', verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('screens', models.ManyToManyField(related_name='playlists', to='screens.screen', verbose_name='Écrans')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content', verbose_name='Contenu')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist', verbose_name='Playlist')),
            ],
            options={
                'verbose_name': 'Élément de playlist',
                'verbose_name_plural': 'Éléments de playlist',
                'ordering': ['order'],
                'unique_together': {('playlist', 'content')},
            },
        ),
    ]
