# Generated by Django 4.2.7 on 2025-12-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screens', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.content', verbose_name='Contenu')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='screens.screen', verbose_name='Écran')),
            ],
            options={
                'verbose_name': "Log d'écran",
                'verbose_name_plural': "Logs d'écrans",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_s_timesta_4caa8a_idx'), models.Index(fields=['screen', '-timestamp'], name='analytics_s_screen__c16cab_idx')],
            },
        ),
    ]
